_commit: v0.7.11
_src_path: gh:Netbeheer-Nederland/tmpl-dp
description: Information models for the NBNL Operation data product.
name: dp-nbnl-operation
org: Netbeheer-Nederland
schema_base_uri: http://modellen.netbeheernederland.nl/operation
title: NBNL Operation (OP)
